### ISSUE TITLE
服务有异常

### ISSUE THREAD

**Issue by weity** [Sensoro/SDK-Android#11]
E/AndroidRuntime(14739): FATAL EXCEPTION: main
E/AndroidRuntime(14739): Process: com.test:remote, PID: 14739
E/AndroidRuntime(14739): java.lang.ClassCastException: android.os.BinderProxy cannot be cast to com.sensoro.beacon.kit.BeaconService$BeaconServiceV4Binder
E/AndroidRuntime(14739):    at com.sensoro.beacon.kit.SensoroBeaconManager$2.onServiceConnected(SourceFile:271)
E/AndroidRuntime(14739):    at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1107)
E/AndroidRuntime(14739):    at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1124)
E/AndroidRuntime(14739):    at android.os.Handler.handleCallback(Handler.java:733)
E/AndroidRuntime(14739):    at android.os.Handler.dispatchMessage(Handler.java:95)
E/AndroidRuntime(14739):    at android.os.Looper.loop(Looper.java:136)
E/AndroidRuntime(14739):    at android.app.ActivityThread.main(ActivityThread.java:5032)
E/AndroidRuntime(14739):    at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime(14739):    at java.lang.reflect.Method.invoke(Method.java:515)
E/AndroidRuntime(14739):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
E/AndroidRuntime(14739):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
E/AndroidRuntime(14739):    at dalvik.system.NativeStart.main(Native Method)

**Comment by weity** [comment]
demo 和项目冲突，把demo删了就好了
